name: Deployment workflow
on:
    push:
        branches: [ main ]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-20.04
        steps:
            - name: ssh command
              uses: appleboy/ssh-action@master
              with:
                  host: simon-svirkov.com
                  username: admin
                  key: ${{ secrets.SSH_SECRET}}
                  port: 22
                  script: |
                      cd /var/www/
                      git pull origin main
                      git status

